### PR TITLE
Cleanup path separators in gopass response #122

### PR DESCRIPTION
**Pull request by AuspeXeu**

### CODE REVIEW

**Comment by Pharb** [comment]
@AuspeXeu Thanks for taking a look at the code and finding a possible solution.

From looking at your change it seems that the problem is caused by gopass returning inconsistent paths as responses?

@martinhoefling probably has better insight into this, but I would guess that something around here is not properly handled on Windows? https://github.com/gopasspw/gopass/blob/v1.8.6/pkg/jsonapi/responses.go#L78

Maybe we can add a temporary workaround into gopassbridge, but also a long-term fix for gopass?

I'm not sure if there are valid cases for having `\` within a gopass secret name/path?

**Comment by martinhoefling** [comment]
@AuspeXeu thx for trying to fix that issue. As @Pharb  mentioned, the issue has probably multiple causes. One is that in https://github.com/gopasspw/gopass/blob/v1.8.6/pkg/jsonapi/responses.go#L21, where we're hardcoding the separator. This probably breaks detection of usernames on windows (from the path).
To me, replacing \ with / looks more like a short term fix. I would rather prefer if the gopass api returns the secret path platform specific and parsing in gopassbridge can deal with both cases.

**Comment by martinhoefling** [comment]
I have created https://github.com/gopasspw/gopass/pull/1166, can you check if it changes something? However, it's still not clear to me why you get mixed path seps. I currently have no Windows machine to try out.

**Comment by AuspeXeu** [comment]
How can I help you testing?

**Comment by AuspeXeu** [comment]
Is there any chance we could have this merged so that gopass is at least usable for the time being until/if the windows separator issue is ever addressed?

**Comment by Pharb** [comment]
Sorry for letting you wait so long @AuspeXeu.

The fundamental problem is sadly still the unclear state of Windows support for gopass, mostly due to lack of gopass maintainers using Windows.

 I guess your workaround here is reasonable enough, maybe we could change that the transformation only happens on Windows? Currently only ~10% of our gopassbridge users are on Windows, and I want to avoid the risk of breaking use cases on Linux/Mac.

Also it would be great if you could rebase your branch on master and sign-off the commit message as described here: https://github.com/gopasspw/gopassbridge/pull/123/checks?check_run_id=195297763

Thanks for your help 👍

**Comment by AuspeXeu** [comment]
Should be all good now. Let me know if you need anything further to go ahead with this :)

**Comment by Pharb** [comment]
Thanks for the update, last thing left to do would be to add a new test case to cover both branches of the new `if` statement and maybe try to extract the condition into a separate function to make the `codeclimatet` check happy. I could also do that for your, if necessary.

**Comment by AuspeXeu** [comment]
I tried looking at these test cases but to be honest I am a bit lost there...

**Comment by Pharb** [comment]
No problem, I'll see what I can do 😃

**Comment by martinhoefling** [comment]
I have added a test and created a PR against your branch https://github.com/AuspeXeu/gopassbridge/pull/1

**Comment by martinhoefling** [comment]
We need to do more cleanup and @AuspeXeu, you have to signoff your commit

**Comment by AuspeXeu** [comment]
Done.

**Comment by AuspeXeu** [comment]
Seems like we're ticking all the boxes finally :)

**Comment by Pharb** [comment]
LGTM 👍 
Thanks a lot for the collaboration @AuspeXeu!

**Pull request merged**
