### PR TITLE
Add tooltips to search result buttons

### PR DESCRIPTION
**Pull request by kristiankostadinov**
As mentioned in #73

### CODE REVIEW

**Comment by Pharb** [comment]
Thanks a lot @kristiankostadinov for your effort to improve the UI.

I will try to review your changes in the next few days, but until then it would help a lot if you could provide some screenshots showing your UI changes in Chrome and Firefox and post them here as comments.

**Comment by kristiankostadinov** [comment]
Hi, here are some screenshots:

### Chrome
chrome
### Firefox
firefox

**Comment by martinhoefling** [comment]
@kristiankostadinov , looks really nice! Thx.

**Comment by Pharb** [comment]
Looks good, thanks 👍

**Comment by Pharb** [comment]
Thanks again @kristiankostadinov, your changes are now live on Firefox in v0.7.0, Chrome release is still pending review...

**Pull request merged**
